<template>
  <div>
    <b-card title="Cross-Disciplinary Access">
      <b-card title="Goals">
        <b-card-text>
          To improve cross-disciplinary research outcomes by linking data across repositories using a range of tools, and vocabularies.
        </b-card-text>
        <b-card title="Metrics">
          <b-card-text>
          Clear documentation of workflows for GeoDeepDive-based annotation
          Number of annotations generated by cross-disciplinary linking activity
          Number of end user workshops held and number of participants
          Number of data repositories linked through cross-disciplinary annotations.
          </b-card-text>
        </b-card>
      </b-card>
    </b-card>
  </div>
</template>

<script>

  export default {
    name: 'crossDiscip',
    props: {
      msg: String
    }
  }

</script>
