<template>
  <div class="hello">
    <h1>Throughput Metrics</h1>
    This project is to be evaluated using Project Metrics defined in the Throughput project proposal.

    <h2>Annotation infrastructure</h2>
    <h3>Goal</h3>

    <ul>
      <li>Improving the cyberinfrastructure required to maintain and serve an Annotation database for the Earth Sciences.</li>
    </ul>

    <h3>METRICS</h3>
    <ul>
      <li>Development of a testing suite for the database and fully integrated development/production system.</li>
      <li>Clear documentation for online collaboration and protocols for bug reporting.</li>
      <li>Adoption and management of a Project Board system.</li>
      <li>Public database landing page with key reporting metrics (data volume, query speeds, etc.)</li>
    </ul>

    <h3>GOAL</h3>
    Building user interfaces to support user groups within the earth sciences including:

    <h2>Direct annotation</h2>
    <h3>The Earth Science Cookbook.</h3>
    <h4>METRICS</h4>
    <ul>
    <li>Direct annotation landing page built and tagged in a version control system (GitHub), with Usability report from the UMN Usability Lab.</li>
    <li>Documentation surrounding the usability report.</li>
    <li>Earth Science Cookbook UI built and tagged in version control system.</li>
    <li>Usability report from the Usability Lab.</li>
    </ul>

    <h3>Workflow Discovery</h3>
    <h4>GOAL</h4>
    Establishing a platform to support the addition of workflow elements to the TAE and to link primary data resources in the geosciences through publicly available code.

    <h4>METRICS</h4>
    <ul>
    <li>Number of scripts recovered by programmatic workflows</li>
    <li>Number of user-submitted scripts</li>
    <li>Number of data resources connected through scripts</li>
    <li>Number of users accessing scripts through the system</li>
    <li>Number of workshops (and number of participants) that use annotation as an element in instruction.</li>
    </ul>

    <h3>Cross-Disciplinary Access</h3>
    <h4>GOAL</h4>
    To improve cross-disciplinary research outcomes by linking data across repositories using a range of tools, and vocabularies.

    <h4>METRICS</h4>
    Clear documentation of workflows for GeoDeepDive-based annotation
    Number of annotations generated by cross-disciplinary linking activity
    Number of end user workshops held and number of participants
    Number of data repositories linked through cross-disciplinary annotations.
  </div>
</template>

<script>
export default {
  name: 'HelloWorld',
  props: {
    msg: String
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: circle;
  padding: 0;
}
li {
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>
