<template>
  <div class="hello">
    <h1>Throughput Metrics</h1>
    This project is to be evaluated using Project Metrics defined in the Throughput project proposal (<a href="https://nsf.gov/awardsearch/showAward?AWD_ID=1928366">NSF-1928366</a>).

    <met-anno />
    <h3>Cross-Disciplinary Access</h3>
    <h4>GOAL</h4>
    To improve cross-disciplinary research outcomes by linking data across repositories using a range of tools, and vocabularies.

    <h4>METRICS</h4>
    Clear documentation of workflows for GeoDeepDive-based annotation
    Number of annotations generated by cross-disciplinary linking activity
    Number of end user workshops held and number of participants
    Number of data repositories linked through cross-disciplinary annotations.
  </div>
</template>

<script>
import annotationVue from './annotation.vue'

export default {
  name: 'parentPage',
  props: {
    msg: String
  },
  components: {
    'met-anno': annotationVue,
  }
}

</script>
